FROM node:18-alpine

RUN apk add --no-cache sqlite sqlite-dev

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 4000

CMD ["sh", "-c", "npx prisma migrate deploy && npm run dev"]
